#define UART_NUM UART_NUM_0
#define UART_BUFFER_SIZE 256
#define UART_BAUD_RATE 115200
#define UART_QUEUE_SIZE 10

#define UART_TAG "UART"
#define PID_TAG "PID"
#define NVS_TAG "NVS"

#define DEVICE_DATA_NAMESPACE "device_data"
#define DEVICE_ADDRESS "address"

#define PWM_FREQ 50
#define DUTY_RESOLUTION LEDC_TIMER_14_BIT
#define VALVE0_PIN GPIO_NUM_4
#define VALVE0_CHANNEL LEDC_CHANNEL_0
#define VALVE1_PIN GPIO_NUM_5
#define VALVE1_CHANNEL LEDC_CHANNEL_1
#define VALVE2_PIN GPIO_NUM_6
#define VALVE2_CHANNEL LEDC_CHANNEL_2
#define VALVE3_PIN GPIO_NUM_7
#define VALVE3_CHANNEL LEDC_CHANNEL_3
#define VALVE4_PIN GPIO_NUM_15
#define VALVE4_CHANNEL LEDC_CHANNEL_4
#define VALVE5_PIN GPIO_NUM_16
#define VALVE5_CHANNEL LEDC_CHANNEL_5
#define VALVE6_PIN GPIO_NUM_17
#define VALVE6_CHANNEL LEDC_CHANNEL_6
#define VALVE7_PIN GPIO_NUM_18
#define VALVE7_CHANNEL LEDC_CHANNEL_7